# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f96797af92309f273338de03aa2c1dc88d146e689701be56251d4e482f3a809c6ceaa46d68393b8c84cdbc6ed961e8602959221b361b1bda4ea14f8ce54caffe

test:
  secret_key_base: 5c80ff107f63e9b174fdea001ed2370aadbe7eacd628b8f9fb39852102ac8c558e3fa2683b63fe1d49b5cdfcbbdccea646c124f8940c8e020d6070a8cbd0de48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
